[mypy]
python_version = 3.8
pretty = True
allow_redefinition = False
check_untyped_defs = True
disallow_any_generics = True
disallow_incomplete_defs = True
ignore_missing_imports = True
implicit_reexport = False
strict_optional = True
strict_equality = True
no_implicit_optional = True
warn_no_return = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
warn_return_any = True
warn_unreachable = True
show_error_codes = True
show_column_numbers = True
show_error_context = True

[mypy-torch.*]
follow_imports = skip
follow_imports_for_stubs = True

[mypy-fulmo.core.module]
ignore_errors = True

[mypy-fulmo.utils.logging]
ignore_errors = True

[mypy-fulmo.samplers.balanced]
ignore_errors = True

[mypy-fulmo.losses.online_smooth]
ignore_errors = True
